### ISSUE TITLE
Added functions

### ISSUE THREAD

**Issue by faquin** [samcarton/miami-nights-pebble#1]
Hi, thanks for the great watch face, I like it a lot. The only thing is I think the date is a bit awkward the way it is shown.
So I have forked your code and updated it to remove the date.
I have also added bluetooth events, I like when my Pebble Time warn me about phone disconnection. 
I am currently using my customized watchface base on this code https://github.com/faquin/miami-nights-pebble/

**Comment by samcarton** [comment]
Hi @faquin , glad you like it :) I plan on making the face configurable at some point so I may pull in your changes.

**Comment by faquin** [comment]
Hi
I have deleted my branch, and created a new one to make things clearer. I have created separate commits, so it will be easier to pull what you want.
All the best.
